apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hawkbit.fullname" . }}
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
{{ toYaml .Values.config.application | indent 4}}
  # Add custom hawkbit configuration here
