apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hawkbit.fullname" . }}
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hawkbit.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "hawkbit.name" . }}
        release: {{ .Release.Name }}
      {{- with .Values.podTemplate.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: hawkbit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PROFILES
              value: "{{ .Values.spring.profiles }}"
            - name: "SPRING_DATASOURCE_URL"
              {{- if .Values.env.springDatasourceUrl }}
              value: "{{ .Values.env.springDatasourceUrl }}"
              {{- else }}
              value: "jdbc:mariadb://{{ if .Values.mysql.enabled }}{{ .Release.Name }}-mysql{{ else }}{{ .Values.env.springDatasourceHost }}{{ end }}:3306/{{ .Values.env.springDatasourceDb }}"
              {{- end }}
            - name: "SPRING_APPLICATION_JSON"
              valueFrom:
                secretKeyRef:
                  name: {{ include "hawkbit.fullname" . }}
                  key: "SPRING_APPLICATION_JSON"
            {{- if .Values.rabbitmq.enabled }}
            - name: "SPRING_RABBITMQ_HOST"
              value: "{{ .Release.Name }}-rabbitmq"
            - name: "SPRING_RABBITMQ_USERNAME"
              value: "{{ .Values.env.springRabbitmqUsername }}"
            - name: "SPRING_RABBITMQ_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ template "hawkbit.fullname" . }}-rabbitmq-pass"
                  key: "rabbitmq-pass"
            {{- end }}
            {{- if .Values.fileStorage.enabled }}
            - name: "org.eclipse.hawkbit.repository.file.path"
              value: {{ .Values.fileStorage.mountPath }}
            {{- end }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:{{ .Values.configMap.mountPath }}/application.yaml"
            {{- range $key, $value := .Values.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "hawkbit.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
