{{- if .Values.initDb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hawkbit.fullname" . }}-init-db
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "hawkbit.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: {{ .Values.initDb.image }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://{{ .Values.mariadb.host }}:{{ .Values.mariadb.port }}/{{ .Values.mariadb.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.mariadb.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.mariadb.password }}
{{- end }}
