apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hawkbit.fullname" . }}
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "hawkbit.name" . }}
      release: {{ .Release.Name }}

{{- end }}
