apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.config.secrets }}
  SPRING_APPLICATION_JSON: {{ .Values.config.secrets | toJson | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-rabbitmq-pass
  labels:
    app: {{ include "hawkbit.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.env.springRabbitmqPassword }}
  rabbitmq-pass: {{ .Values.env.springRabbitmqPassword | b64enc | quote }}
  {{- end }}
