apiVersion: v1
kind: Service
metadata:
  name: {{ include "hawkbit.simpleui.fullname" . }}
  labels:
    app: {{ include "hawkbit.simpleui.name" . }}
    chart: {{ include "hawkbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.serviceSimpleUI.annotations | nindent 4 }}
spec:
  type: {{ .Values.serviceSimpleUI.type }}
  ports:
    - port: {{ .Values.serviceSimpleUI.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: {{ include "hawkbit.simpleui.name" . }}
    release: {{ .Release.Name }}
