apiVersion: v2
name: hawkbit
version: 1.9.9
appVersion: "0.9.0"
description: |
  Eclipse hawkBitâ„¢ Helm chart for Kubernetes
  - Supports MariaDB, MinIO, Keycloak, Simple UI
  - Compatible with Kubernetes >= 1.22
  - Uses only stable APIs (policy/v1, networking.k8s.io/v1)
  - Includes init-db job for schema setup
  - Highly configurable via values.yaml
keywords:
  - hawkbit
  - ota
  - update-server
  - helm
  - kubernetes
  - iot-chart
sources:
- https://github.com/eclipse/hawkbit
- https://github.com/eclipse/packages
icon: https://www.eclipse.org/hawkbit/images/hawkbit_icon.png
maintainers:
- name: monotek
  email: andre.bauer@kiwigrid.com
- name: axdotl
  email: axel.koehler@kiwigrid.com
- name: ctron
  email: ctron@dentrassi.de
- name: Fabio Craviolatti
  email: fabio.craviolatti@lutech.it
dependencies:
- name: mysql
  version: ^13.x
  repository: "oci://registry-1.docker.io/bitnamicharts"
  condition: mysql.enabled
- name: rabbitmq
  version: ^16.x
  repository: "oci://registry-1.docker.io/bitnamicharts"
  condition: rabbitmq.enabled
