# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: EPL-2.0
---
# Default values for hawkbit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "hawkbit/hawkbit-update-server"
  tag: '0.9.0'
  pullPolicy: IfNotPresent
  initContainer: "hawkbit/hawkbit-repository-jpa-init"

simpleUIImage:
  repository: "hawkbit/hawkbit-simple-ui"
  tag: "0.9.0"
  pullPolicy: IfNotPresent

replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

securityContext:
  enabled: true
  fsGroup: 65534
  runAsUser: 65534
  extra: {}

updateStrategy:
  type: RollingUpdate

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  annotations: {}

serviceSimpleUI:
  type: ClusterIP
  port: 8088
  annotations: {}

livenessProbe:
  initialDelaySeconds: 240
  timeoutSeconds: 5
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

ingress:
  enabled: true
  ingressClassName: traefik
  annotations: {}
  hosts:
    - host: hawkbit.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podTemplate:
  annotations: {}

extraVolumes: []
extraVolumeMounts: []

configMap:
  mountPath: "/config"

spring:
  profiles: "mariadb"

config:
  application:
    server:
      useForwardHeaders: true
    hawkbit:
    spring:
      cloud:
        stream:
          bindings:
            default:
              group: "hawkbit"

mariadb:
  host: hawkbit-mariadb
  port: 3306
  database: hawkbit
  username: hawkbit
  password: hawkbit-db-password-2026

minio:
  host: hawkbit-minio-hl
  port: 9000
  accessKey: minio-access-key
  secretKey: minio-secret-key

keycloak:
  enabled: false
  url: ""


extraEnv: []
